apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: weather-app
  name: weather-app
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/dev-weather/weather-app:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source